config/routes.rb
Adwordsassistant::Application.routes.draw do

  get "document_featured_image/:id" => 'admin/documents#featured_image', :as => 'document_image'

  get "audio_featured_image/:id" => 'admin/audios#featured_image', :as => 'audio_image'
  
  get "video_featured_image/:id" => 'admin/videos#featured_image', :as => 'video_image'
  
  get "article_featured_image/:id" => "admin/articles#featured_image",  :as => "article_image"
  
  get "post_featured_image/:id" => "admin/posts#featured_image",  :as => "post_image"
  
  get "section_cpmv/:id" => "admin/sections#section_cpmv", :as => "section_cpmv"

  get "publication/:publication_id/post/:post_id/comment/:id" => 'admin/comments#status', :as => "comment/status"
  

resources :reviews, :only => :show
resources :topics do
  resources :groups do 
    resources :copies 
  end
end

resources :banners, :only => :show

resources :copies

resources :keywords
    
devise_for :users, :controllers => { :registrations => "admin/registrations" }

 namespace :admin do

    resources :clients
    resources :reviews
    
    resources :banners
    resources :gifs
    resources :swfs
    resources :keywords

    resources :users do 
      post :generate_new_password_email
    end

    resources :topics do
      resources :groups do 
        resources :copies 
      end
      collection {post :import}
      collection {post :keywords}
    end

    resources :groups
    resources :copies
    
    resources :dashboard, :only => :index
    
    resources :navigations

    resources :css, :only => [:index, :update]
    
    resources :faqs
    
    resources :testimonials 
    
    resources :categories 
    
    resources :assets

    resources :helps
    
    resources :images 

    resources :audios

    resources :documents

    resources :links
    
    resources :footers
    
    resources :forms do 
      resources :fields
    end

    resources :fieldOptions, controller: 'field_options'
    
    resources :sliders do
      resources :slides
    end

    resources :slides
    
    resources :comments
    
    resources :youtubes
    
    resources :settings

    resources :collections

    resources :versions, :only => [:index, :show]
    
    resources :rewrites

    resources :notes
    resources :responses
    
    resources :pages do
        post :sort, on: :collection
        resources :sections do
          post :sort, on: :collection
          resources :contents
        end
      end
      
    resources :footers do
      resources :sections do
        resources :contents
      end
    end

    resources :multi_navigations do
        resources :sections do
          resources :contents
        end
    end
      
    resources :shared_contents do
        resources :sections do
          resources :contents
        end
    end

    resources :publications do 
      resources :posts do 
        resources :comments   
      end
        resources :sections do
          resources :contents
        end
    end
    resources :sections
    # resources :fieldOptions

  end

  get 'restore' => 'admin/versions#undo_destroy', :as => 'undo'

  resources :comments, only: [:new, :create, :show]


  get 'search' => 'search#index', :as => 'search'

  get "submit" => "site#submit_form", :as => "submit"

  get "publication/:publication_id/:id" => "posts#show", :as => "post/show"

  get "publication/:publication_id/category/:id" => "posts#category", :as => "post/category"

  get  '*url_path' => 'site#show'
  
  root :to => 'site#show'
end

app/models/topic.rb
class Topic < ActiveRecord::Base

  extend FriendlyId
    friendly_id :name, use: :slugged

  default_scope { order('id DESC') }

  has_many :groups, :dependent => :destroy
  has_many :reviews, :dependent => :destroy

  belongs_to :client

  after_create :create_review_url


  def create_review_url
    review = Review.new
    review.topic_id = self.id
    review.save
  end


  def self.get_user(id)
    @user = User.find(id)
  end

  def self.import(file)
    if(file)
      xls = nil
      case File.extname(file.original_filename)
        when ".xls" then xls = Roo::Spreadsheet.open(file.path, extension: :xls)
        when ".xlsx" then xls = Roo::Spreadsheet.open(file.path, extension: :xlsx)
        else raise "Unknown file type: #{file.original_filename}"
      end

      if xls
        xls.each(:ad => '^Description$',:description_1 => '^Headline 1$',:description_2 => '^Headline 2$',:ad_group => '^Ad group$', :campaign => '^Campaign$', :display_url => '^Final URL$', :destination_url => '^Final URL', :ad_id => "^Ad ID$", :ad_group_id => "^Ad group ID$", :ad_type => "^Ad type$") do |hash|
          #only import text ads
          if hash[:ad_type] == "Expanded text ad"
            unless hash[:campaign] == " --" || hash[:campaign] == "Campaign" || hash[:campaign] == nil
              topic = Topic.find_by_name hash[:campaign]
              if !topic
                  topic = Topic.new
                  topic.name = hash[:campaign]
                  puts "New #{topic.name}"

              end

              topic.save

              group = Group.find_by_ad_group_id hash[:ad_group_id]
              if !group
                group = Group.new
              end

              group.name = hash[:ad_group]
              group.ad_group_id = hash[:ad_group_id]
              group.destination_url = hash[:destination_url]
              group.display_url = hash[:destination_url].split("/")[2]
              group.network = "Google"
              topic.groups << group

              group.save

              content =  hash[:description_1] + " - "+ hash[:description_2]  + "\n" + hash[:ad]

              copy = Copy.find_by_ad_id hash[:ad_id]
              if !copy
                copy = Copy.new
                copy.selected = true
              end

              copy.ad_id = hash[:ad_id]
              copy.content = content
              copy.editor = @user.email
              group.copies << copy

            end
          end
        end
      end
    end
  end

  def self.keywords(file)
    if(file)
      xls = nil
      case File.extname(file.original_filename)
        when ".xls" then xls = Roo::Spreadsheet.open(file.path, extension: :xls)
        when ".xlsx" then xls = Roo::Spreadsheet.open(file.path, extension: :xlsx)
        else raise "Unknown file type: #{file.original_filename}"
      end

      if xls
        xls.each(:campaign => 'Campaign', :keyword => '^Keyword$', :ad_group => 'Ad group', :keyword_id => '^Keyword ID$',:ad_group_id => '^Ad group ID$') do |hash|

          unless hash[:campaign] == " --" || hash[:campaign] == "Campaign" || hash[:campaign] == nil
            topic = Topic.find_by_name hash[:campaign]
            if !topic
                topic = Topic.new
                topic.name = hash[:campaign]
                puts "New #{topic.name}"
            end

            topic.save

            unless hash[:ad_group] == nil

              group = Group.find_by_name hash[:ad_group]
              if !group
                group = Group.new
                group.save
              end

              group.name = hash[:ad_group]
              group.ad_group_id = hash[:ad_group_id]
              group.network = "Google"
              topic.groups << group

              if group.keywords !=nil

                keyword = Keyword.find_by_keyword_id(hash[:keyword_id])

                if keyword == nil
                  puts "KEYWORD IS NIL NOT FOUND"
                  keyword = Keyword.new
                  keyword.group_id = group.id
                  keyword.word = hash[:keyword]
                  keyword.is_chosen = 1
                  keyword.under_review = 0
                  keyword.keyword_id = hash[:keyword_id]
                  keyword.ad_group_id = hash[:ad_group_id]
                  keyword.save
                else
                  puts "Keyword NOT NIL - FOUND"
                  keyword.group_id = group.id
                  keyword.word = hash[:keyword]
                  keyword.is_chosen = 1
                  keyword.under_review = 0
                  keyword.keyword_id = hash[:keyword_id]
                  keyword.ad_group_id = hash[:ad_group_id]
                  keyword.save
                end


                # group.keywords += "#{hash[:keyword]}\n"
              # else
              #   group.keywords = "#{hash[:keyword]}\n"
              end
              group.save
            end
          end
        end
      end
    end
  end

  # def to_csv(topic)
  #   CSV.generate do |csv|
  #     csv << ['Ad state','Ad', 'Description line 1', 'Description line 2', 'Display URL', 'Destination URL', 'Campaign', 'Ad group', 'Status']
  #     topic.groups.where(:selected => true).each do |group|
  #      group.copies.each do |copy|
  #       con = copy.content.lines.map(&:chomp)
  #       csv << ['enabled', con[0], con[1], con[2], group.display_url, group.destination_url, topic.name, group.name, 'approved']
  #      end
  #     end
  #   end
  # end

end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :topic_params, :only => :create
  authorize_resource
  layout 'admin/admin'
  
  def index
    @topics = Topic.all 
    @title = "Topics"
  end
  
  def show
    @topic = Topic.friendly.find(params[:id])
    @title = @topic.name
    respond_to do |format|
      format.html
      format.xls
      format.xlsx
    end
  end
  
  def new
    @topic = Topic.new
    @clients = Client.all
    render :layout => false
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save 
      flash[:success]= "Successfully created topic."
    end
    respond_to do |format|
      if @topic.save
        format.html {redirect_to admin_topics_path}
        format.js
      else
        @title = "New Topic"
        format.html { render :action => :new }
        format.js
      end
    end 
  end

  def edit
    @topic = Topic.friendly.find(params[:id])
    @title = @topic.name
    @clients = Client.all
    render :layout => false
  end 
  
  def update 
    @topic = Topic.friendly.find(params[:id])
    if @topic.update_attributes(topic_params)
      flash[:success]= "Successfully updated topic."
      redirect_to admin_topics_path()
    else
      render :action => 'edit'
      @title = "Edit Topic"
    end
  end


  def destroy
    @topic = Topic.friendly.find(params[:id])
    @topic.destroy
    redirect_to admin_topics_path
  end

  def topic_params
    params.require(:topic).permit(:name, :client_id)
  end

  def import
    Topic.get_user(params[:user])
    Topic.import(params[:file])
    if params[:file]
      flash[:success] = "Campaign imported"
    else
      flash[:error] = "No file chosen."
    end
    redirect_to admin_topics_path
  end

  def keywords
    Topic.keywords(params[:file])
    if params[:file]
      flash[:success] = "Keywords imported"
    else
      flash[:error] = "No file chosen."
    end
    redirect_to admin_topics_path
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def show

    # possible
    # @topic_slug  = Review.find_by_hash(hash_id)
    # @topic = Topic.friendly.find(topic_slug)

    @topic = Topic.friendly.find(params[:id])
    @title = @topic.name
  end

end

app/helpers/topics_helper.rb
module TopicsHelper

  def to_alphabet(i)
    alpha = ("A".."Z").to_a
    return alpha[i]
  end

  def selected_version(selected, i)
    if selected
      content_tag(:span, "Version #{to_alphabet(i)}", :class =>"selected-version")
    else
      content_tag(:span, "Version #{to_alphabet(i)}", :class =>"non-selected-version")
    end
  end

  def green_or_red(i)

    if i == 0
      content_tag(:span, "✕", :class =>"label label-negative")
    else
      content_tag(:span, "✓", :class =>"label label-positive")
    end
    
  end

end

app/views/admin/topics/_alt_copy.html.haml
%strong
  Alternate Copy  
=simple_format copy.content
%strong
  Editor:
=copy.editor
%br/
%strong
  Date:
= copy.created_at.strftime("%b %d, %I:%M %P")

app/views/admin/topics/_checkboxes.html.haml
-if copy.selected
  =image_tag("checkbox-checked.png")
-else
  =image_tag("checkbox.png")

app/views/admin/topics/_copy.html.haml
.tabbable 
  %ul.nav.nav-tabs
    %li.active
      %a
        Original
        =render partial: "admin/topics/index_of_copy", locals: {copy: copy, index: index}
        =render partial: "admin/topics/checkboxes", locals: {copy: copy, index: index}

  .tab-content
    .tab-pane.active
      .copy-content
        =render partial: "admin/topics/content_per_network", locals: {group: group, copy: copy}
        =render partial: "admin/topics/editor", locals: {group: group, copy: copy}
        
        .clear-both
        =render partial: "admin/topics/selected_form", locals: {copy: copy}
        .btn-group
          =link_to content_tag(:i,'',:class => 'fontello-icon-edit') + " Edit", edit_admin_topic_group_copy_path(@topic, group, copy), :class => "btn btn-sky btn-mini edit-copy fboxForm fancybox.ajax", :data => {:textarea => "copy_content", :network => "#{group.network}"}

          =link_to content_tag(:i,'',:class => 'fontello-icon-trash-4') +' Delete', admin_topic_group_copy_path(@topic,group, copy),  data: { confirm: 'Are you sure?' }, :method => :delete, :class => "btn btn-mini btn-danger"
        

app/views/admin/topics/_dates.html.haml
-if group.start_date || group.end_date
  .post-dates.clear-both
    -if group.start_date.length > 0 && group.end_date.length > 0
      Post Date:
      =group.start_date
      \-
      =group.end_date
    -elsif group.start_date.length > 0
      Post Date:
      =group.start_date

app/views/admin/topics/_duplicates.html.haml
=render partial: "admin/topics/content_per_network", locals: {group: group, copy: copy}
=render partial: "admin/topics/editor", locals: {group: group, copy: copy}

app/views/admin/topics/_editor.html.haml
%strong
  Date:
= copy.created_at.strftime("%b %d, %I:%M %P")

app/views/admin/topics/_facebook_ad.html.haml
.facebook-ad-display
  =image_tag group.image
  =facebook_ad_content(copy.content, group.display_url)

app/views/admin/topics/_facebook_post.html.haml
.facebook-post-display
  =facebook_post_content copy.content, group.display_url
  =image_tag group.image

app/views/admin/topics/_index_of_copy.html.haml
-if copy.selected
  %span.index-of-copy.selected
    =index + 1
-else
  %span.index-of-copy
    =index + 1

app/views/admin/topics/_network.html.haml
=group.network

app/views/admin/topics/_selected_form.html.haml
=form_for [:admin, copy] do |f|
  %label.inline
    =f.check_box :selected, :class => 'submittable'
    Selected
  =f.submit :style => 'display:none;width:0;'

app/views/admin/topics/_tabbed_versions.html.haml
.tabbable 
  %ul.nav.nav-tabs
    -copy.alternates.where(:is_duplicate => "true").each_with_index do |c,i|
      -if i == 0
        %li.active
          %a{:href => "#v#{c.id}", :data => {:toggle => "tab"}}
            =selected_version(c.selected, i)
            =render partial: "admin/topics/checkboxes", locals: {copy: c, index: index}

      -else
        %li
          %a{:href => "#v#{c.id}", :data => {:toggle => "tab"}}
            =selected_version(c.selected, i)
            =render partial: "admin/topics/checkboxes", locals: {copy: c, index: index}

  .tab-content
    -copy.alternates.where(:is_duplicate => "true").each_with_index do |c ,i|
      -if i == 0
        %div{:class => 'tab-pane active', :id => "v#{c.id}"}
          =render partial: "admin/topics/duplicates", locals: {group: group, copy: c} 
          -if current_user
            =render partial: "admin/topics/selected_form", locals: {group: group, copy: c}

      -else
        %div{:class => 'tab-pane', :id => "v#{c.id}"}
          =render partial: "admin/topics/duplicates", locals: {group: group, copy: c}
          -if current_user
            =render partial: "admin/topics/selected_form", locals: {group: group, copy: c}

app/views/admin/topics/_twitter.html.haml
.twitter-display
  -if group.is_card
    .card
      %p
        =copy.content
      .tweet-image
        =image_tag group.image
      =link_to group.display_url, group.destination_url, :class => 'btn'
  -else
    .tweet
      .headline
        =image_tag "twitter-default.png"
        %span.t-client
          TEST
        %span.t-at
          @theTweeter 
        %span.t-date
          Jun 14
      .t-content 
        =copy.content
        =link_to group.display_url, group.destination_url
        .t-footer
          =image_tag "tweet-bottom.png"

app/views/admin/topics/show.html.haml
:javascript
  $(document).ready(function() {
    var clip = new ZeroClipboard($("#copy-button"))
  });

=content_for :page_title do
  %h1.page-title
    -if @topic.client
      =@topic.client.name
      \:
    =@topic.name
    
.navbar.navbar-page
  .navbar-inner
    .container
      %ul.nav.pull-right
        %li.divider-vertical

        %li
          = link_to "Review Mode", "#", :id => 'review-mode'
        %li.divider-vertical
        %li
          = link_to content_tag(:i,'',:class => 'fontello-icon-download-cloud') + "XLSX", admin_topic_path(@topic, format: "xlsx")

#topic-show
  #form-remote.widget.widget-box
    .widget-content
      .widget-body
        =link_to "New Group", new_admin_topic_group_path(@topic), :class => 'pull-right btn btn-yellow pull-right btn-mini fboxForm fancybox.ajax new-groups'
        .clear-both
        -if @topic.groups.count > 0
          %ul.widget-list
            -@topic.groups.each do |group|

              %li{:id => "group-#{group.id}", :class => "group"}
                .group-name.clear-both
                  %h2
                    =group.name
                    =group.id

                    =render partial: "admin/topics/network", locals: {group: group}

                  .btn-group
                    =link_to content_tag(:i,'',:class => 'fontello-icon-pencil') + " New", new_admin_topic_group_copy_path(@topic, group), :class => "btn btn-yellow btn-mini new-copy fboxForm fancybox.ajax",:remote => true, :data => {:textarea => "copy_content", :network => "#{group.network}"}

                    =link_to content_tag(:i,'',:class => 'fontello-icon-edit') + " Edit", edit_admin_topic_group_path(@topic, group), :class => 'btn btn-sky  btn-mini fboxForm fancybox.ajax '

                    =link_to content_tag(:i,'',:class => 'fontello-icon-trash-4') +' Delete', admin_topic_group_path(@topic, group),  data: { confirm: 'Are you sure?' }, :method => :delete, :class => "btn btn-mini btn-danger"

                    = link_to content_tag(:i,'',:class => 'fontello-icon-download') + " Selected Group(s)",admin_group_path(group,format: "xlsx",:keywords_only => false), :class => 'btn btn-mini btn-green'

                
                  -if (group.network == 'Google')
                    .keywords.span3
                      %strong
                        Keywords:
                        .btn-group
                          =link_to "+ New", new_admin_keyword_path(:group_id => group.id), :class => 'btn btn-mini btn-green fboxForm fancybox.ajax '
                          = link_to content_tag(:i,'',:class => 'fontello-icon-download') + " Keywords",admin_group_path(group,format: "xlsx",:keywords_only => true), :class => 'btn btn-mini btn-green'
                          
                      -if (group.keywords.count > 0)
                        %table
                          %thead
                            %th
                              Word                         
                          -group.keywords.each do |keyword|
                            %tr
                              %td
                                -if keyword.is_chosen == 1
                                  =content_tag(:span, "✓", :class =>"label label-positive")
                                -if keyword.is_chosen != 1
                                  =content_tag(:span, "✕", :class =>"label label-negative")
                                =link_to keyword.word, edit_admin_keyword_path(keyword), :class => 'fboxForm fancybox.ajax '
                              %td
                                

                              
                            
                            


                -if (group.network == 'Google')
                  -span = "span8"
                -else
                  -span = "span11"
                  
                %div{:class => "copies #{span}"}
                
                  -if group.copies.count > 0  
                    %ul.group-copy
                      -group.copies.where(:copy_id => 0).each_with_index do |copy, index|
                        %li
                          -if copy.alternates.where(:is_duplicate => "true").count > 0
                            .col-50

                              =render partial: "admin/topics/copy", locals: {group: group, copy: copy, index: index}
                              

                            .col-50.dups
                              =render partial: "admin/topics/tabbed_versions", locals: {group: group, copy: copy, index: index}
                              %h1
                                copyid
                                =copy.copy_id
                              
                          -else

                            =render partial: "admin/topics/copy", locals: {group: group, copy: copy, index: index}

                          -if copy.alternates.where(:is_duplicate => "false").count > 0
                            %ul.alt-group-copy
                              -copy.alternates.where(:is_duplicate => "false").each do |c|
                                %li.span4
                                  =render partial: "admin/topics/alt_copy", locals: {group: group, copy: c, index: index}
                                  
                =render partial: "admin/topics/dates", locals: {group: group}

    .widget-footer
      -if @topic.reviews.length > 0 && @topic.groups.count > 0
        %h3
          Review Url

        = "#{request.protocol + request.host}/reviews/#{@topic.reviews.first.url}"
        %br/
        %button{:class => "btn btn-primary", :id => "copy-button", :data => {"clipboard-text" => "#{request.protocol + request.host}/reviews/#{@topic.reviews.first.url}"}, :title => "Click to copy review URL to clipboard."}
          Copy to Clipboard
      / .span4
      /   =link_to content_tag(:i,'',:class => 'fontello-icon-mail') +' Client Review', "#", :class => "btn btn-yellow send-to"

      / #send-to.span4

      /   %p
      /     Enter email address one line at a time. No commas or periods after email address.
      /     =form_tag admin_reviews_path do |f|
      /       =text_area_tag "users"
      /       =hidden_field_tag "topic_id", @topic.id
      /       =submit_tag "Send", :class =>'btn btn-primary'


        