config/routes.rb
Adwordsassistant::Application.routes.draw do

  get "document_featured_image/:id" => 'admin/documents#featured_image', :as => 'document_image'

  get "audio_featured_image/:id" => 'admin/audios#featured_image', :as => 'audio_image'
  
  get "video_featured_image/:id" => 'admin/videos#featured_image', :as => 'video_image'
  
  get "article_featured_image/:id" => "admin/articles#featured_image",  :as => "article_image"
  
  get "post_featured_image/:id" => "admin/posts#featured_image",  :as => "post_image"
  
  get "section_cpmv/:id" => "admin/sections#section_cpmv", :as => "section_cpmv"

  get "publication/:publication_id/post/:post_id/comment/:id" => 'admin/comments#status', :as => "comment/status"
  

resources :reviews, :only => :show
resources :topics do
  resources :groups do 
    resources :copies 
  end
end

resources :banners, :only => :show

resources :copies

resources :keywords
    
devise_for :users, :controllers => { :registrations => "admin/registrations" }

 namespace :admin do

    resources :clients
    resources :reviews
    
    resources :banners
    resources :gifs
    resources :swfs
    resources :keywords

    resources :users do 
      post :generate_new_password_email
    end

    resources :topics do
      resources :groups do 
        resources :copies 
      end
      collection {post :import}
      collection {post :keywords}
    end

    resources :groups
    resources :copies
    
    resources :dashboard, :only => :index
    
    resources :navigations

    resources :css, :only => [:index, :update]
    
    resources :faqs
    
    resources :testimonials 
    
    resources :categories 
    
    resources :assets

    resources :helps
    
    resources :images 

    resources :audios

    resources :documents

    resources :links
    
    resources :footers
    
    resources :forms do 
      resources :fields
    end

    resources :fieldOptions, controller: 'field_options'
    
    resources :sliders do
      resources :slides
    end

    resources :slides
    
    resources :comments
    
    resources :youtubes
    
    resources :settings

    resources :collections

    resources :versions, :only => [:index, :show]
    
    resources :rewrites

    resources :notes
    resources :responses
    
    resources :pages do
        post :sort, on: :collection
        resources :sections do
          post :sort, on: :collection
          resources :contents
        end
      end
      
    resources :footers do
      resources :sections do
        resources :contents
      end
    end

    resources :multi_navigations do
        resources :sections do
          resources :contents
        end
    end
      
    resources :shared_contents do
        resources :sections do
          resources :contents
        end
    end

    resources :publications do 
      resources :posts do 
        resources :comments   
      end
        resources :sections do
          resources :contents
        end
    end
    resources :sections
    # resources :fieldOptions

  end

  get 'restore' => 'admin/versions#undo_destroy', :as => 'undo'

  resources :comments, only: [:new, :create, :show]


  get 'search' => 'search#index', :as => 'search'

  get "submit" => "site#submit_form", :as => "submit"

  get "publication/:publication_id/:id" => "posts#show", :as => "post/show"

  get "publication/:publication_id/category/:id" => "posts#category", :as => "post/category"

  get  '*url_path' => 'site#show'
  
  root :to => 'site#show'
end

app/models/multi_navigation.rb
class MultiNavigation < ActiveRecord::Base
	has_many :sections
	has_one :page

	validates :title, :presence => true
	validates :dynamic_content_width, :presence => true

	# attr_accessible :title, :show_sub_pages, :sub_pages_location, :sub_nav_width, :dynamic_content_width
end

app/controllers/admin/multi_navigations_controller.rb
class Admin::MultiNavigationsController < ApplicationController

	before_filter :authenticate_user!
	before_filter :multi_nav_params, :only => :create
	load_and_authorize_resource
	layout 'admin/admin'

	def index
		@multi_navigations = MultiNavigation.order(:id)
		@title = "Multi-Navigations"
	end

	def show
		@multi_navigation = MultiNavigation.find(params[:id])
	end

	def new
		@multi_navigation = MultiNavigation.new
		@title = "New multi-navigation"
		render :layout => false
	end

	def create
		if @multi_navigation.save 
			flash[:success]= "Successfully created multi-navigation menu."
		end
		respond_to do |format|
			if @multi_navigation.save
      			format.html {redirect_to admin_multi_navigations_path}
				format.js
			else
				@title = "New multi-navigation"
				format.html { render :action => :new }
				format.js
			end
		end
	end

	def edit
		@title = "Edit multi-navigation"
		render :layout => false
	end

	def update 
		if @multi_navigation.update_attributes(multi_nav_params)
			flash[:success]= "Successfully updated multi-navigation menu."
		end
		respond_to do |format|
			if @multi_navigation.save
				# redirect for editing on navigation/:id/sections
				if params[:redirect]
					format.html {redirect_to admin_multi_navigation_sections_path(@multi_navigation)}
				else
					format.html {redirect_to  admin_multi_navigations_path}
				end
				format.js
			else
				@title = "Edit multi-navigation"
				format.html { render :action => :edit }
				format.js
			end
		end
	end
	
	def destroy
		@multi_navigation.destroy
		pages = Page.where(:multi_navigation_id => @multi_navigation)
		pages.each do |p|
			p.update_attributes(:multi_navigation_id => '')
		end
		sections = Section.where(:multi_navigation_id => @multi_navigation)
		sections.each do |s|
			s.destroy
		end
		redirect_to admin_multi_navigations_path
	end

	def multi_nav_params
		params.require(:multi_navigation).permit!
	end
end

app/views/admin/multi_navigations/_form_fields.html.haml
=javascript_include_tag 'admin/modal_links.js'

%ul.form-list.label-left.list-bordered.form-horizontal
	%li.control-group	
		=f.label "Title *", :class => "control-label"
		.controls
			=f.text_field :title, :class => 'required'
	%li.control-group
		=f.label :sub_nav_width, :class => "control-label"
		.controls
			=f.text_field :sub_nav_width
			%span
				px
			.help-block
				Width of sub-navigation links if you choose to show them.
	%li.control-group
		=f.label "Dynamic Content Width *", :class => "control-label"
		.controls
			=f.text_field :dynamic_content_width, :class => 'required'
			%span
				px
			.help-block
				Width of the content you will or have created.

	%li.control-group
		=f.label :show_sub_pages, :class => "control-label"	
		.control
			=f.check_box :show_sub_pages
			.help-block
				If unchecked dynamic content width will be used for multi-navigation container width.

	%li.control-group	
		.help-block
			If you are using sub-navigation links do you want the links
		%label.radio
			=f.radio_button :sub_pages_location, 1
			Before mulit-navigation content

		%label.radio	
			=f.radio_button	:sub_pages_location, 2
			After mulit-navigation content

app/views/admin/multi_navigations/_multi_navigation.html.haml
%table{:id => 'sortable-table',:class => "table table-striped table-hover table-bordered boo-table"}
  %caption
    Mulit-navigations (Mega dropdown navigation)
  %thead
    %th
      Actions
    %th{:scope => 'col'}
      Title
      %span.column-sorter
    %th
      Page settings
    %th
      Public facing view
    
  -@multi_navigations.each_with_index do | mn, i|
    %tr
      %td
        .btn-group
          =link_to content_tag(:span, '', :class => 'caret') + " Action", '#',:class => "btn dropdown-toggle btn-yellow", 'data-toggle' => "dropdown"
          %ul.dropdown-menu
            %li
              =link_to content_tag(:i,'',:class => 'fontello-icon-cog-alt') + " Edit multi-navigation", edit_admin_multi_navigation_path(mn),:class => 'fboxForm fancybox.ajax'
            %li
              =link_to content_tag(:i,'',:class => 'fontello-icon-article') + " Edit multi-navigation content",admin_multi_navigation_sections_path(mn)
            %li.divider
            %li
              =link_to content_tag(:i,'',:class => 'fontello-icon-trash-4') + " Delete multi-navigation", admin_multi_navigation_path(mn),:data => {:confirm => 'Are you sure?'}, :method => :delete, :class => 'delete'

      %td
        =mn.title.capitalize
      %th
        -if mn.page 
          =link_to content_tag(:i,'',:class => 'fontello-icon-cog-alt') + " Page #{mn.page.title.capitalize} settings", edit_admin_page_path(mn.page.id), :class => 'fboxPages fancybox.ajax btn btn-mini btn-sky'
        %th
          -if mn.page
            %a{:title => mn.page.title, :href => mn.page.url_path,:target => '_blank', :class => 'btn btn-mini btn-sky'} 
              =content_tag(:i,'',:class => 'fontello-icon-link-1')
              =mn.page.title
          

app/views/admin/multi_navigations/edit.html.haml
#form-remote
  =form_for [:admin, @multi_navigation], :html => {:id => "multi_navigation"} do |f|
    -if(params[:sections])
      =hidden_field_tag :redirect, "sections"
    .modal-header
      =link_to content_tag(:i, '',:class => "fontello-icon-cancel" ),'', :class=> "close close-form", 'aria-hidden' => "true"
      %h4
        =@multi_navigation.title
    .modal-body
      -if @multi_navigation
        =render 'shared/error_messages', :object => @multi_navigation 
      =render "admin/multi_navigations/form_fields", :f => f
    .modal-footer
      =f.submit "Save", :class =>'btn btn-primary'

app/views/admin/multi_navigations/index.html.haml
=content_for :page_title do
  %h1.page-title
    Multi-navigations
.navbar.navbar-page
  .navbar-inner
    .container
      %ul.nav.pull-right
        %li.divider-vertical
        %li
          =link_to content_tag(:i,'',:class => 'fontello-icon-plus-1') + ' New multi-navigation',new_admin_multi_navigation_path, :class => 'fboxForm fancybox.ajax'
   
=render 'multi_navigation'

app/views/admin/multi_navigations/new.html.haml
#form-remote
  =form_for [:admin, @multi_navigation] do |f|
    .modal-header
      =link_to content_tag(:i, '',:class => "fontello-icon-cancel" ),'', :class=> "close close-form", 'aria-hidden' => "true"
      %h4
        New Multi-navigations
    .modal-body
      -if @multi_navigation
        =render 'shared/error_messages', :object => @multi_navigation 
      =render "admin/multi_navigations/form_fields", :f => f
    .modal-footer
      =f.submit "Save", :class =>'btn btn-primary'