config/routes.rb
Adwordsassistant::Application.routes.draw do

  get "document_featured_image/:id" => 'admin/documents#featured_image', :as => 'document_image'

  get "audio_featured_image/:id" => 'admin/audios#featured_image', :as => 'audio_image'
  
  get "video_featured_image/:id" => 'admin/videos#featured_image', :as => 'video_image'
  
  get "article_featured_image/:id" => "admin/articles#featured_image",  :as => "article_image"
  
  get "post_featured_image/:id" => "admin/posts#featured_image",  :as => "post_image"
  
  get "section_cpmv/:id" => "admin/sections#section_cpmv", :as => "section_cpmv"

  get "publication/:publication_id/post/:post_id/comment/:id" => 'admin/comments#status', :as => "comment/status"
  

resources :reviews, :only => :show
resources :topics do
  resources :groups do 
    resources :copies 
  end
end

resources :banners, :only => :show

resources :copies

resources :keywords
    
devise_for :users, :controllers => { :registrations => "admin/registrations" }

 namespace :admin do

    resources :clients
    resources :reviews
    
    resources :banners
    resources :gifs
    resources :swfs
    resources :keywords

    resources :users do 
      post :generate_new_password_email
    end

    resources :topics do
      resources :groups do 
        resources :copies 
      end
      collection {post :import}
      collection {post :keywords}
    end

    resources :groups
    resources :copies
    
    resources :dashboard, :only => :index
    
    resources :navigations

    resources :css, :only => [:index, :update]
    
    resources :faqs
    
    resources :testimonials 
    
    resources :categories 
    
    resources :assets

    resources :helps
    
    resources :images 

    resources :audios

    resources :documents

    resources :links
    
    resources :footers
    
    resources :forms do 
      resources :fields
    end

    resources :fieldOptions, controller: 'field_options'
    
    resources :sliders do
      resources :slides
    end

    resources :slides
    
    resources :comments
    
    resources :youtubes
    
    resources :settings

    resources :collections

    resources :versions, :only => [:index, :show]
    
    resources :rewrites

    resources :notes
    resources :responses
    
    resources :pages do
        post :sort, on: :collection
        resources :sections do
          post :sort, on: :collection
          resources :contents
        end
      end
      
    resources :footers do
      resources :sections do
        resources :contents
      end
    end

    resources :multi_navigations do
        resources :sections do
          resources :contents
        end
    end
      
    resources :shared_contents do
        resources :sections do
          resources :contents
        end
    end

    resources :publications do 
      resources :posts do 
        resources :comments   
      end
        resources :sections do
          resources :contents
        end
    end
    resources :sections
    # resources :fieldOptions

  end

  get 'restore' => 'admin/versions#undo_destroy', :as => 'undo'

  resources :comments, only: [:new, :create, :show]


  get 'search' => 'search#index', :as => 'search'

  get "submit" => "site#submit_form", :as => "submit"

  get "publication/:publication_id/:id" => "posts#show", :as => "post/show"

  get "publication/:publication_id/category/:id" => "posts#category", :as => "post/category"

  get  '*url_path' => 'site#show'
  
  root :to => 'site#show'
end

app/models/image.rb
class Image < ActiveRecord::Base

  before_save :update_image_attributes

  belongs_to :document
  has_one :document_image
  
  
  # post join models and association
  has_many :post_images, :dependent => :destroy
  has_many :posts, :through => :post_images

  has_many :slides
  
	# Categories join models and association for categories
	has_many :asset_categories, :as => :categorizable, :dependent => :destroy
	has_many :categories, :through => :asset_categories 
	  
	validates :title,  :presence => true
	validates :image,  :presence => true

	mount_uploader :image, ImageUploader

	attr_accessor :asset
	attr_accessor :asset_id
	attr_accessor :image_size
	attr_accessor :publication_id

	after_save :set_asset
	after_destroy :check_sliders

	# attr_accessible :title,:image, :caption, :description, :image_cache, :remove_image, 
	# :category_ids, :asset, :asset_id, :publication_id, :image_size, :image_id, :post_id

	private

	def set_asset
		#pre written for images for assets just not used 9-11-2012
		if @asset == "document"
			document = DocumentImage.find_by_document_id(@asset_id)
			if document
				document.update_attributes(:image_id => self.id, :document_id => @asset_id, :image_size => @image_size )
			else
				document = DocumentImage.new
				document.update_attributes(:image_id => self.id, :document_id => @asset_id, :image_size => @image_size )
			end
		end
		# if @asset == "audio"
		# 	audio = AudioImage.find_by_audio_id(@asset_id)
		# 	if audio
		# 		audio.update_attributes(:image_id => self.id, :audio_id => @asset_id, :image_size => @image_size )
		# 	else
		# 		audio = AudioImage.new
		# 		audio.update_attributes(:image_id => self.id, :audio_id => @asset_id, :image_size => @image_size )
		# 	end
		# end
		# if @asset == "video"
		# 	video = VideoImage.find_by_video_id(@asset_id)
		# 	if video
		# 		video.update_attributes(:image_id => self.id, :video_id => @asset_id, :image_size => @image_size )
		# 	else
		# 		video = VideoImage.new
		# 		video.update_attributes(:image_id => self.id, :video_id => @asset_id, :image_size => @image_size )
		# 	end
		# end
		
		if @asset == "post"
			post = PostImage.find_by_post_id(@asset_id)
			if post
				post.update_attributes(:image_id => self.id, :post_id => @asset_id, :image_size => @image_size )
			else
				post = PostImage.new
				post.update_attributes(:image_id => self.id, :post_id => @asset_id, :image_size => @image_size )
			end
		end
	end

	def check_sliders
		slider = Slide.find_by_image_id(self.id)
		if slider
			slider.destroy
		end
	end

 private

  def update_image_attributes
    if image.present? && image_changed?
      self.content_type = image.file.content_type
      self.file_size = image.file.size
    end
  end

end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < ApplicationController

	before_filter :authenticate_user!
	before_filter :image_params, :only => :create
	authorize_resource

	layout 'admin/admin'
	
	def index
		if params[:image].present?
		    @image = Image.find(params[:image])
		    render :action => 'edit'
	    else
	    	@images = Image.order(:title) 
			@title = "Images"
		end
	end
	
	def show
		@title = @image.title
	end
	
	def new
		@image = Image.new
		render :layout => false
	end

	def create
			@image = Image.new(image_params)
	    if @image.save
	      	if params[:image][:asset] == 'document'
		     	redirect_to admin_documents_path
		     	flash[:success] = "Successfully updated document image."
		     	
		     elsif params[:image][:asset] == 'audio'
		     	redirect_to edit_admin_audio_path(params[:image][:asset_id])
		     	flash[:success] = "Successfully updated audio image."
		     	
		     elsif params[:image][:asset] == 'video'
		     	redirect_to edit_admin_video_path(params[:image][:asset_id])
		     	flash[:success] = "Successfully updated video image."
		     			     	
		      elsif params[:image][:asset] == 'post'
		     	post = Post.find(params[:image][:asset_id])
		     	redirect_to edit_admin_publication_post_path(post.publication_id,params[:image][:asset_id])
		     	flash[:success] = "Successfully uploaded Post image."		     	
		     else
		     	flash[:success] = "Successfully uploaded image."
		     	respond_to do |format|
      				format.html {redirect_to admin_images_path} 
      				format.js
    			end 
	      end
	    else
	      @title = "New Image"
	      render :action => 'new' 
	    end
	end

	def edit
		@image = Image.find(params[:id])
		@title = @image.title
		render :layout => false
	end	
	
	def update 
		params[:image][:category_ids] ||= []
		@image = Image.find(params[:id])
	      if @image.update_attributes(image_params)
		     if params[:image][:asset] == 'document'
		     	redirect_to edit_admin_document_path(params[:image][:asset_id])
		     	flash[:success] = "Successfully updated document image."
		     	
		     elsif params[:image][:asset] == 'audio'
		     	redirect_to edit_admin_audio_path(params[:image][:asset_id])
		     	flash[:success] = "Successfully updated audio image."
		     	
		     elsif params[:image][:asset] == 'video'
		     	redirect_to edit_admin_video_path(params[:image][:asset_id])
		     	flash[:success] = "Successfully updated video image."
		     	
		     	
		     elsif params[:image][:asset] == 'post'
		     	post = Post.find(params[:image][:asset_id])
		     	redirect_to edit_admin_publication_post_path(post.publication_id,params[:image][:asset_id])
		     	flash[:success] = "Successfully updated Post image."

		     else 
		      flash[:success] = "Successfully updated image."
		      respond_to do |format|
      				format.html {redirect_to admin_images_path()} 
      				format.js
    			end
	      	 end
	      else
			render :action => 'edit'
			@title = "Edit Image"
	    end
	end

	def destroy
		@image.destroy
		redirect_to admin_images_path
	end
	
	
	def featured_image
	 	@publication = Publication.find(params[:publication_id])
	 	@post = Post.find(params[:post_id])
	 	@image = Image.find(params[:id])
		render :layout => false
	end

	def image_params
		params.require(:image).permit(:title,:image, :caption, :description, :image_cache, :remove_image, :asset, :asset_id, :publication_id, :image_size, :image_id, :post_id,:category_ids => [])
	end
end

app/views/admin/images/_form_fields.html.haml
=javascript_include_tag 'admin/modal_links.js'

%ul.form-list.label-left.list-bordered.form-horizontal
  %li.control-group
    =f.label "Image *", :class => "control-label"
    .controls
      -if controller.action_name == 'new'
        -required = 'required'
      =f.file_field :image,:class => required
      
  %li.control-group
    =f.label "Title *", :class => "control-label"
    .controls
      =f.text_field :title , :class => 'required'
      .help-block
        Title is used for search.
    
  %li.control-group
    =f.label :caption, :class => "control-label"
    .controls
      =f.text_field :caption
  
  %li.control-group
    =f.label :description
    .controls
      =f.text_area :description, :rows => 3

%ul.form-list.label-left.list-bordered
  %li.section-form
    %h4
      Categories
  %li.control-group
    -categories = Category.where('image = 1') 
    -if categories.count > 0
      -categories.each do |cat|
        %label.checkbox.inline
          =check_box_tag "image[category_ids][]",cat.id, @image.categories.include?(cat), :id => cat.id, :class => 'checkbox'
          =cat.name   
      .help-block
        Check category to update asset.
    -else
      %p
        No categories assoicated with images.
        =link_to 'Go to categories', admin_categories_path,:class => 'btn btn-yellow'

app/views/admin/images/_images.html.haml
%div{:id => "images"}
  %table{:id => 'sortable-table',:class => "table table-striped table-hover table-bordered boo-table"}
    %caption
      Images
    %thead
      %th
        Actions
      %th{:scope => 'col'}
        Title
        %span.column-sorter
      %th
        Image 
        %small
          Thumbnail
      %th{:scope => 'col'}
        Categories
        %span.column-sorter
      
    -@images.each_with_index do |image, i|
      %tr
        %td
          .btn-group
            =link_to content_tag(:i,'',:class => 'fontello-icon-pencil-1') + ' Edit',edit_admin_image_path(image), :class => 'fboxForm fancybox.ajax btn btn-mini btn-yellow'
            =link_to content_tag(:i,'',:class => 'fontello-icon-trash-4') +' Delete', admin_image_path(image),:data => {:confirm => 'Are you sure?'}, :method => :delete, :class => 'btn btn-mini btn-danger'
        %td
          =image.title
        %td
          =image_tag(image.image_url(:thumb))
        %td
          =image.categories.collect{|c| c.name}.join(', ')

app/views/admin/images/edit.html.haml
#form-remote
  =form_for [:admin, @image], :html => {:id => "edit_image"} do |f|
    .modal-header
      =link_to content_tag(:i, '',:class => "fontello-icon-cancel" ),'', :class=> "close close-form", 'aria-hidden' => "true"
      %h4
        =@image.title
    .modal-body
      -if @image
        =render 'shared/error_messages', :object => @image 
      =render "admin/images/form_fields", :f => f
    .modal-footer
      =f.submit "Save", :class =>'btn btn-primary'

app/views/admin/images/index.html.haml
=content_for :page_title do
  %h1.page-title
    Images
.navbar.navbar-page
  .navbar-inner
    .container
      %ul.nav.pull-right
        %li.divider-vertical
        %li
          =link_to content_tag(:i,'',:class => 'fontello-icon-upload') + ' New image',new_admin_image_path, :class => 'fboxForm fancybox.ajax'
   
=render 'images'

app/views/admin/images/new.html.haml
#form-remote
  =form_for [:admin, @image] do |f|
    .modal-header
      =link_to content_tag(:i, '',:class => "fontello-icon-cancel" ),'', :class=> "close close-form", 'aria-hidden' => "true"
      %h4
        New Image
    .modal-body
      -if @image
        =render 'shared/error_messages', :object => @image 
      =render "admin/images/form_fields", :f => f
    .modal-footer
      =f.submit "Save", :class =>'btn btn-primary'