config/routes.rb
Adwordsassistant::Application.routes.draw do

  get "document_featured_image/:id" => 'admin/documents#featured_image', :as => 'document_image'

  get "audio_featured_image/:id" => 'admin/audios#featured_image', :as => 'audio_image'
  
  get "video_featured_image/:id" => 'admin/videos#featured_image', :as => 'video_image'
  
  get "article_featured_image/:id" => "admin/articles#featured_image",  :as => "article_image"
  
  get "post_featured_image/:id" => "admin/posts#featured_image",  :as => "post_image"
  
  get "section_cpmv/:id" => "admin/sections#section_cpmv", :as => "section_cpmv"

  get "publication/:publication_id/post/:post_id/comment/:id" => 'admin/comments#status', :as => "comment/status"
  

resources :reviews, :only => :show
resources :topics do
  resources :groups do 
    resources :copies 
  end
end

resources :banners, :only => :show

resources :copies

resources :keywords
    
devise_for :users, :controllers => { :registrations => "admin/registrations" }

 namespace :admin do

    resources :clients
    resources :reviews
    
    resources :banners
    resources :gifs
    resources :swfs
    resources :keywords

    resources :users do 
      post :generate_new_password_email
    end

    resources :topics do
      resources :groups do 
        resources :copies 
      end
      collection {post :import}
      collection {post :keywords}
    end

    resources :groups
    resources :copies
    
    resources :dashboard, :only => :index
    
    resources :navigations

    resources :css, :only => [:index, :update]
    
    resources :faqs
    
    resources :testimonials 
    
    resources :categories 
    
    resources :assets

    resources :helps
    
    resources :images 

    resources :audios

    resources :documents

    resources :links
    
    resources :footers
    
    resources :forms do 
      resources :fields
    end

    resources :fieldOptions, controller: 'field_options'
    
    resources :sliders do
      resources :slides
    end

    resources :slides
    
    resources :comments
    
    resources :youtubes
    
    resources :settings

    resources :collections

    resources :versions, :only => [:index, :show]
    
    resources :rewrites

    resources :notes
    resources :responses
    
    resources :pages do
        post :sort, on: :collection
        resources :sections do
          post :sort, on: :collection
          resources :contents
        end
      end
      
    resources :footers do
      resources :sections do
        resources :contents
      end
    end

    resources :multi_navigations do
        resources :sections do
          resources :contents
        end
    end
      
    resources :shared_contents do
        resources :sections do
          resources :contents
        end
    end

    resources :publications do 
      resources :posts do 
        resources :comments   
      end
        resources :sections do
          resources :contents
        end
    end
    resources :sections
    # resources :fieldOptions

  end

  get 'restore' => 'admin/versions#undo_destroy', :as => 'undo'

  resources :comments, only: [:new, :create, :show]


  get 'search' => 'search#index', :as => 'search'

  get "submit" => "site#submit_form", :as => "submit"

  get "publication/:publication_id/:id" => "posts#show", :as => "post/show"

  get "publication/:publication_id/category/:id" => "posts#category", :as => "post/category"

  get  '*url_path' => 'site#show'
  
  root :to => 'site#show'
end

app/models/youtube.rb
class Youtube < ActiveRecord::Base
	
	has_and_belongs_to_many :sections
	has_many :asset_categories, :as => :categorizable, :dependent => :destroy
	has_many :categories, :through => :asset_categories

  validates :title,  :presence => true 
end

app/controllers/admin/youtubes_controller.rb
class Admin::YoutubesController < ApplicationController

	before_filter :authenticate_user!
  before_filter :youtube_params, :only => :create
	authorize_resource
	layout 'admin/admin'
	
  def index
    @youtubes = Youtube.order(:id)
    @title = "YouTube Videos"
  end
  
  def new
    @youtube = Youtube.new
    render :layout => false
  end
  
	def create 
    @YouTube = @youtube = Youtube.new(youtube_params)
		if @youtube.save 
			flash[:success]= "Youtube has been submitted."
      redirect_to admin_youtubes_path
		else
      @title = "New Youtube"
      render :action => :new 
    end
	end
	
	def edit
    @youtube = Youtube.find(params[:id])
		@title = "Update Youtube"
    render :layout => false
	end
	
	def update
    @youtube = Youtube.find(params[:id])
		if @youtube.update_attributes(youtube_params)
			flash[:success]= "Successfully updated youtube."
      redirect_to admin_youtubes_path()
      else
        render :action => 'edit'
        @title = "Edit Youtube"
      end
	end
	
	def destroy
    @youtube = Youtube.find(params[:id])
    @youtube.asset_categories.each do |ac|
      ac.destroy
    end
    @youtube.destroy
    flash[:success] = "Successfully removed youtube."
    redirect_to admin_youtubes_path
	end

  def youtube_params
    params.require(:youtube).permit(:title, :youtube_code, :category_ids => [])
  end
	
end

app/views/admin/youtubes/_form_fields.html.haml
=javascript_include_tag 'admin/modal_links.js'

%ul.form-list.label-left.list-bordered.form-horizontal
  %li.control-group
    =f.label "Title *", :class => "control-label"
    .controls
      =f.text_field :title,:class => 'required'
      .help-block
        Title will be used for identification when inserting into slideshows or content areas.
  %li.control-group
    =f.label :youtube_code, :class => "control-label"
    .controls
      =f.text_field :youtube_code
      .help-block
        Should be only 11 characers long and NOT include 'http://youtu.be/'.
%ul.form-list.label-left.list-bordered
  %li.section-form
    %h4
      Categories
  %li.control-group
    -categories = Category.where('video = 1') 
    -if categories.count > 0
      -categories.each do |cat| 
        %label.checkbox.inline
          =check_box_tag "youtube[category_ids][]",cat.id, @youtube.categories.include?(cat), :id => cat.id, :class => 'checkbox'
          =cat.name   
      .help-block
        Check category to update asset.
    -else
      %p
        No categories associated with YouTube videos.
        =link_to 'Go to categories', admin_categories_path,:class => 'btn btn-yellow'

app/views/admin/youtubes/_youtubes.html.haml
%div{:id => "youtubes"}
	%table{:id => 'sortable-table',:class => "table table-striped table-hover table-bordered boo-table"}
		%caption
			YouTube Videos
		%thead
			%th
				Actions
			%th{:scope => 'col'}
				Title
				%span.column-sorter
			%th
				Categories
			
		-@youtubes.each_with_index do |youtube, i|
			%tr
				%td
					.btn-group
						=link_to content_tag(:i,'',:class => 'fontello-icon-pencil-1') + ' Edit',edit_admin_youtube_path(youtube), :class => 'fboxForm fancybox.ajax btn btn-mini btn-yellow'
						=link_to content_tag(:i,'',:class => 'fontello-icon-trash-4') +' Delete', admin_youtube_path(youtube),:data => {:confirm => 'Are you sure?'}, :method => :delete, :class => 'btn btn-mini btn-danger'
				%td
					=youtube.title
				%td
					=youtube.categories.collect{|c| c.name}.join(', ')

app/views/admin/youtubes/edit.html.haml
#form-remote
  =form_for [:admin, @youtube], :html => {:id => "edit_youtube"} do |f|
    .modal-header
      =link_to content_tag(:i, '',:class => "fontello-icon-cancel" ),'', :class=> "close close-form", 'aria-hidden' => "true"
      %h4
        =title
    .modal-body
      -if @youtube
        =render 'shared/error_messages', :object => @youtube 
      =render "admin/youtubes/form_fields", :f => f
    .modal-footer
      =f.submit "Save", :class =>'btn btn-primary'

app/views/admin/youtubes/index.html.haml
=content_for :page_title do
  %h1.page-title
    YouTube
.navbar.navbar-page
  .navbar-inner
    .container
      %ul.nav.pull-right
        %li.divider-vertical
        %li
          =link_to content_tag(:i,'',:class => 'fontello-icon-youtube') + ' New Youtube',new_admin_youtube_path, :class => 'fboxForm fancybox.ajax'
   
=render 'youtubes'

app/views/admin/youtubes/new.html.haml
#form-remote
  =form_for [:admin, @youtube] do |f|
    .modal-header
      =link_to content_tag(:i, '',:class => "fontello-icon-cancel" ),'', :class=> "close close-form", 'aria-hidden' => "true"
      %h4
        =title
    .modal-body
      -if @youtube
        =render 'shared/error_messages', :object => @youtube 
      =render "admin/youtubes/form_fields", :f => f
    .modal-footer
      =f.submit "Save", :class =>'btn btn-primary'